In [1]:
import torch
from torch import Tensor

In [2]:
a = Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

In [3]:
b = Tensor([[7, 8, 9], [0, 1, 2],])

In [4]:
torch.stack([a, b])

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[7., 8., 9.],
         [0., 1., 2.]]])

In [5]:
c = a.unsqueeze(dim=1)
d = b.unsqueeze(dim=1)

In [6]:
torch.cat([c, d])

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]],

        [[0., 1., 2.]]])

In [7]:
c

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])

In [8]:
for i in range(3):
    print(i)

0
1
2
